POST http://localhost:3001/api/todo HTTP/1.1
Content-Type: application/json

{
  "content": "Mira mamá me estoy convirtiendo en Full Stack developer",
  "userId": "61500009fba0bb0a87c9b643"
}

###

POST http://localhost:3001/api/todo HTTP/1.1
Content-Type: application/json

{
  "content": "post with content and complete",
  "complete": true
}